version: '3.4'
x-db-variables: &db-variables
  MYSQL_DATABASE: 'cs4230'
  MYSQL_USER: 'cs4230-user'
  MYSQL_PASSWORD: 'password'
  MYSQL_PORT:
services:
  mysql:
    image: mysql:8.0.20
    volumes:
      - cs4230-db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      <<: *db-variables
      MYSQL_ROOT_PASSWORD: 'password'
volumes:
  cs4230-db:
