spring:
  api:
    title: Spring Boot APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: com.abc.controller
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
    swagger:
      enable: true
  application:
    name: cms
  datasource:
    url: jdbc:mysql://localhost:3306/cs4230
    username: cs4230-user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    flyway:
      baseline-on-migrate: true
      schemas: cs4230
      user: ${spring.datasource.username}
      url: ${spring.datasource.url}
security:
  jwt:
    token:
      secret-key: AScaklasdAS*(@#$!
      ttl: 30m
server:
  port: 8080