spring:
  application:
    name: cms
  datasource:
    url: jdbc:mysql://localhost:3306/cs4230
    username: cs4230-user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    flyway:
      baseline-on-migrate: true
      schemas: cs4230
      user: ${spring.datasource.username}
      url: ${spring.datasource.url}
security:
  jwt:
    token:
      secret-key: AScaklasdAS*(@#$!
      ttl: 30m
server:
  port: 8081
  error:
    whitelabel:
      enabled: false
app:
  api:
    title: CMS APIs
    version: 1.0.0
    description: CMS APIs
    base-package: com.group1_cms.cms_antiques.controllers
    contact-name: Group1
    contact-email: group1@gmail.com
    swagger:
      enable: true